### ISSUE TITLE
运行时报错

### ISSUE THREAD

**Issue by packaaa** [codexu/x-build#11]
rimraf dist && x-service-serve

(node:16340) UnhandledPromiseRejectionWarning: Error: spawn ./node_modules/.bin/webpack-dev-server ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
(node:16340) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:16340) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

node v10.13.0
x-build v4.6.2
win10

**Comment by codexu** [comment]
windows兼容性问题，已经修复，请更新最新版本
