### ISSUE TITLE
npm run dev 报错 properties 问题

### ISSUE THREAD

**Issue by Shay0921** [codexu/x-build#6]
通过npm install 安装后，然后npm run dev运行项目，遇到报错如下

TypeError: Cannot read property 'properties' of undefined
    at module.exports (D:\cli\x-build\node_modules\webpack-cli\bin\config-yargs.js:89:48)
    at Object.<anonymous> (D:\cli\x-build\node_modules\webpack-dev-server\bin\webpack-dev-server.js:84:40)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app@0.0.1 dev: `rimraf dist & cross-env NODE_ENV=development webpack-dev-server --mode=development --config webpack.config.js --open`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the app@0.0.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\haigui\AppData\Roaming\npm-cache\_logs\2018-09-25T08_46_22_894Z-debug.log

通过github直接下载项目安装和通过x-build-cli安装，都会遇到这个问题

**Comment by codexu** [comment]
npm install了吗？

**Comment by Shay0921** [comment]
> npm install了吗？

恩呢，都执行正确了，但是npm run dev的时候就会报错
